#!/bin/bash
#This script creates symlink using the config files in the repo as a base.
#Any error with mkdir can be safely disregarded

#some interesting variables


ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SOURCE="${ROOT}/config"
TAR="$HOME/.config"

# Install necessary packages
## installing yay
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay

## install from a list
yay -S --needed -< $ROOT/archpackages.txt
yay -S sl
cat $ROOT/archpackages.txt

## clear unneeded dependencies
yay -Yc

# bash
ln -s $SOURCE/bash/.bashrc $HOME/.bashrc

# alacritty
if [ ! -d "$TAR/alacritty" ]; then
	mkdir $TAR/alacritty
fi
ln -sf $SOURCE/alacritty/alacritty.yml $TAR/alacritty/alacritty.yml

# compton
if [ ! -d "$TAR/compton" ]; then
	mkdir $TAR/compton
fi
ln -sf $SOURCE/compton/compton.conf $TAR/compton/compton.conf

# i3
if [ ! -d "$TAR/i3" ]; then
	mkdir $TAR/i3
fi
ln -sf $SOURCE/i3/config $TAR/i3/config

# mpd
if [ ! -d "$TAR/mpd/playlists" ]; then
	mkdir $TAR/mpd/playlists
fi # creating playlists folder
touch $TAR/mpd/database
ln -sf $SOURCE/mpd/mpd.conf $TAR/mpd/mpd.conf

# ncmpcpp
if [ ! -d "$HOME/.ncmpcpp" ]; then
	mkdir $HOME/.ncmpcpp
fi
ln -sf $SOURCE/ncmpcpp/config $HOME/.ncmpcpp

# polybar
if [[ ! -d "$TAR/polybar" ]]; then
	mkdir $TAR/polybar
fi
ln -sf $SOURCE/polybar/config $TAR/polybar/config
ln -sf $SOURCE/polybar/launch.sh $TAR/polybar/launch.sh

# xbindkeys
ln -sf $SOURCE/xbindkeys/.xbindkeysrc $HOME/.xbindkeysrc

# neovim
ln -sf $SOURCE/nvim/init.vim $TAR/nvim/init.vim
