#!/bin/bash
#This script creates symlink using the config files in the repo as a base.
#Any error with mkdir can be safely disregarded

#some interesting variables

SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/config"
TAR="$HOME/.config"

#alacritty
if [ ! -d "$TAR/alacritty" ]; then
	mkdir $TAR/alacritty
fi
ln -sf $SOURCE/alacritty/alacritty.yml $TAR/alacritty/alacritty.yml

#compton
if [ ! -d "$TAR/compton" ]; then
	mkdir $TAR/compton
fi
ln -sf $SOURCE/compton/compton.conf $TAR/compton/compton.conf

#i3
if [ ! -d "$TAR/i3" ]; then
	mkdir $TAR/i3
fi
ln -sf $SOURCE/i3/config $TAR/i3/config

#mpd
if [ ! -d "$TAR/mpd/playlists" ]; then
	mkdir $TAR/mpd/playlists
fi #creating playlists folder
touch $TAR/mpd/database
ln -sf $SOURCE/mpd/mpd.conf $TAR/mpd/mpd.conf

#polybar
if [[ ! -d "$TAR/polybar" ]]; then
	mkdir $TAR/polybar
fi
ln -sf $SOURCE/polybar/config $TAR/polybar/config
ln -sf $SOURCE/polybar/launch.sh $TAR/polybar/launch.sh

#xbindkeys
ln -sf $SOURCE/xbindkeys/.xbindkeysrc $HOME/.xbindkeysrc
